site_name: Vinyl cutter to T-shirt manual

repo_url: https://github.com/uppsala-makerspace/vevor_vinyl_cutter_to_t_shirt_manual
edit_uri: blob/main/docs/

nav:
  - Home: index.md
  - Steps:
    - Procedure overview: steps/procedure.md
    - 0. Check if Inkcut is already installed: steps/0_check.md
    - 1. Install Inkcut: steps/1_install_inkcut/README.md
    - 2. Set up Inkcut: steps/2_setup_inkcut.md
    - 3. Get t-shirts: steps/3_get_t_shirts.md
    - 4. Get vinyl: steps/4_get_vinyl.md
    - 5. Connect the vinyl cutter: steps/5_connect_vinyl_cutter.md
    - 6. Set up the vinyl cutter: steps/6_setup_vinyl_cutter.md
    - 7. Place foil: steps/7_place_foil.md
    - 8. Set up Inkcut connection: steps/8_setup_inkcut_connection.md
    - 9. Use Inkcut: steps/9_use_inkcut.md
    - 10. Setup heat press: steps/10_setup_heat_press.md
    - 11. Peel the vinyl: steps/11_peel_vinyl.md
    - 12. Transfer vinyl to t-shirt: steps/12_transfer_vinyl_to_t_shirt.md
    - Create an SVG: steps/create_svg/README.md
    - Install Inkscape: steps/install_inkscape.md
    - Use text: steps/use_text.md
  - Misc:
    - Code of conduct: CODE_OF_CONDUCT.md
    - Contributing: CONTRIBUTING.md
    - Data: data/README.md
    - License: LICENSE.md
    - PDFs: pdfs/README.md
    - SVGs: svgs/README.md
    - Text on vinyl cutter: text_on_vinyl_cutter.md
    - Time estimates: time_estimates.md
    - Troubleshooting: troubleshooting/README.md
    - Workshop: workshop/README.md

not_in_nav: |
  misc/foreword/README.md
  misc/theory_cover/README.md
  scripts/README.md
  steps/install_inkcut_notes.md
  steps/setup_inkcut_notes.md
  workshop/letter_to_parents.md

theme:
  name: material
  greetings: Welcome to the vinyl cutter to T-shirt manual
  font:
    text: Lato
    code: JetBrains Mono
  palette:
    primary: black

  logo: svgs/2024_logo_Simple_Black_thumbnail.png

  features:
    - toc.integrate
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.path
    - navigation.footer
    - navigation.expand
    - search.suggest
    - content.code.annotate
    - content.code.copy
    - content.tabs.link
    - content.action.edit
    - content.action.view
    
markdown_extensions:
  - toc:
      toc_depth: 2
      permalink: true
      permalink_title: Anchor link to this section for reference
  - admonition
  - tables
  - attr_list
  - footnotes
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.keys
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg


