flowchart TD
  subgraph get_materials[Get the materials]
    get_vinyl[4.Get vinyl]
    get_t_shirt[3.Get t-shirt]
  end
  subgraph prepare_software[One-time software setup]
    install_inkcut[1.Install inkcut]
    setup_inkcut[2.Setup inkcut]
  end
  subgraph prepare_machines[Prepare machines]
    connect_cutter[5.Connect the vinyl cutter]
    setup_cutter[6.Setup the vinyl cutter]
    setup_heat_press[10.Setup the heat press]
  end
  place_vinyl[7.Place foil]
  setup_inkcut_connection[8.Setup inkcut connection]
  cut[9.Use Inkcut]
  transfer[11.Transfer vinyl to T-shirt]
  done[Done!]


  connect_cutter --> setup_cutter
  install_inkcut --> setup_inkcut
  setup_inkcut --> setup_inkcut_connection
  setup_cutter --> setup_inkcut_connection

  setup_inkcut_connection --> cut
  place_vinyl --> cut

  get_vinyl --> place_vinyl
  get_t_shirt --> transfer

  setup_heat_press --> |15 minutes| transfer
  cut --> transfer

  transfer --> done
