name: Create the PDFs

on:
  push:
    paths:
      - 'docs/**'
      - .github/workflows/create_pdfs.yaml
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v4

      - name: See PDFs are still there
        run: ls docs/pdfs/*.pdf

      - name: Delete PDFs
        run: rm docs/pdfs/*.pdf

      - name: See PDFs are gone
        run: ls docs/pdfs

      - uses: r-lib/actions/setup-r@v2

      - uses: r-lib/actions/setup-pandoc@v2

      - name: Install pdflatex
        run: sudo apt-get install texlive-latex-base texlive-latex-recommended

      - name: Create covers
        run: |
          cd docs/scripts/
          ./create_theory_cover.sh
          cd -
          ls docs/pdfs/

      - name: Install libcurl4-openssl-dev
        run: sudo apt install -qq libcurl4-openssl-dev

      - name: Install libharfbuzz-dev libfribidi-dev
        run: sudo apt install -qq libharfbuzz-dev libfribidi-dev

      - name: Install libfontconfig1-dev
        run: sudo apt install -qq libfontconfig1-dev

      - name: Install devtools
        run: install.packages("devtools")
        shell: Rscript {0}

      - name: Install devtools
        run: install.packages("remotes")
        shell: Rscript {0}

      - name: Install mkdocs2md
        run: remotes::install_github("richelbilderbeek/mkdocs2md")
        shell: Rscript {0}

      - name: Install pdfunite
        run: sudo apt-get install poppler-utils

      - name: Install bookletimposer
        run: sudo apt-get install bookletimposer

      - name: Create PDFs
        run: |
          cd docs/scripts
          ./create_theory_book.sh
          cd -
          ls docs/pdfs/

      - name: Upload books
        uses: actions/upload-artifact@v4
        with:
          name: vinyl_cutter_books.zip
          path: docs/pdfs/*.pdf
